### ISSUE TITLE
Integration does not load calendars after first setup

### ISSUE THREAD

**Issue by thegreatdane6** [RogerSelwyn/O365-HomeAssistant#115]
Hi there,
i just discoverd and intergrated this very useful extension (using v4.1.1). I set everything up, authenticated and that worked perfectly fine. The integration generates the folder containing my calendars, but the calendars do not get created and in the logs i see this error:

```
  Logger: homeassistant.components.calendar
  Source: custom_components/o365/calendar.py:250
  Integration: Calendar (documentation, issues)
  First occurred: 17:08:30 (4 occurrences)
  Last logged: 17:08:31
  
  Error adding entities for domain calendar with platform o365
  Error while setting up o365 platform for calendar
  Traceback (most recent call last):
    File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
      await asyncio.gather(*tasks)
    File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 513, in _async_add_entity
      if entity.unique_id is not None:
    File "/config/custom_components/o365/calendar.py", line 243, in unique_id
      self._check_unique_id(unique_id)
    File "/config/custom_components/o365/calendar.py", line 250, in _check_unique_id
      if entry.unique_id != unique_id:
  AttributeError: 'NoneType' object has no attribute 'unique_id'
```

I did give the calendars a unique deviceId like so:
```
- cal_id: xxxxxxxxxx
  entities:
    - device_id: danes_calendar_123
      end_offset: 24
      name: Dane's Kalender
      start_offset: 0
      track: true
```

am i missing out on any other config or is there something wrong?

**Comment by RogerSelwyn** [comment]
Argghhhh, I'll fix it now

**Comment by RogerSelwyn** [comment]
Should be fixed with - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.1.2

**Comment by RogerSelwyn** [comment]
Just update and restart, you should then be OK.

**Comment by thegreatdane6** [comment]
Thank you very much for your quick acting! I’ll test it right away :)

**Comment by thegreatdane6** [comment]
Works like a charm, thank you!
