### ISSUE TITLE
Will not load

### ISSUE THREAD

**Issue by ChrisMD123** [RogerSelwyn/O365-HomeAssistant#125]
Starting about three days ago, the integration will no longer load. Log traceback:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/config/custom_components/o365/__init__.py", line 81, in async_setup
    await _async_setup_account(hass, account, conf_type)
  File "/config/custom_components/o365/__init__.py", line 168, in _async_setup_account
    is_authenticated = account.is_authenticated
  File "/usr/local/lib/python3.10/site-packages/O365/account.py", line 79, in is_authenticated
    token = self.con.token_backend.get_token()
  File "/usr/local/lib/python3.10/site-packages/O365/utils/token.py", line 94, in get_token
    self.token = self.load_token()  # store the token in the 'token' property
  File "/usr/local/lib/python3.10/site-packages/O365/utils/token.py", line 240, in load_token
    token = self.token_constructor(self.serializer.load(token_file))
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by RogerSelwyn** [comment]
What version of Home Assistant are you using and what version of the O365 integration? 

It looks like a problem with your token, which usually the easiest fix is to delete and re-authorise.

**Comment by ChrisMD123** [comment]
I'm using 2023.3.0 (now 2023.3.1) and the latest release of the integration. The error started a few weeks ago when we were still in the 2023.2s but I didn't think much of it and figured it would resolve on its own.

I'll try the reauthentication route and let you know how it goes.

**Comment by VonGuller** [comment]
My home assistant is:

Home Assistant 2023.3.2
Supervisor 2023.03.1
Operating System 9.5
Käyttöliittymän versio: 20230306.0 - latest

After the latest versions of home assistant and after configuring this integration again with the new way, it seems this integration looses its authentication almost in every reboot. 

Clearing the token and reauthenticating works, but after next reboot these errors appear: 

No token, or token doesn't have all required permissions; requesting authorization for account: Account1
Minimum required permissions not granted: ['Presence.Read', []]

**Comment by RogerSelwyn** [comment]
Can you post the contents of the token with access and refresh token redacted. Is that the full error from the log?

**Comment by RogerSelwyn** [comment]
Also, is your a personal account? Because you can’t use a status or chat sensor if it is. That error indicates that you either haven’t provided presence.read permission or it is a personal account.

**Comment by RogerSelwyn** [comment]
No further information provided, so closing.
