### ISSUE TITLE
All-day events not shown as all-day events

### ISSUE THREAD

**Issue by jensrossbach** [RogerSelwyn/O365-HomeAssistant#139]
I'm using Office 365 integration together with Home Assistant's Calendar Card. What I noticed is that all-day events are not shown as "all-day" but with a time span from 00:00 of the day until 00:00 of the next day. This applies to all calendars made available through the O365 integration (e.g., family calendar, public holidays calendar, birthdays calendar). I have another calendar integration which provides data from ICS calendars and there, all-day events are correctly shown as "all-day".

![image](https://user-images.githubusercontent.com/5118924/236666497-07d7e095-ad35-4e8c-9eaf-cfe78d7c2f91.png)

**Comment by RogerSelwyn** [comment]
I’ll take a look. Very strange

**Comment by RogerSelwyn** [comment]
What version of HA and the O365 integration are you using? It seems to work fine for me. But I assume you are CET Summer Time? So is that on UTC+0 at the moment?

**Comment by jensrossbach** [comment]
I'm currently using Home Assistant version 2023.4.6 and O365 integration version 4.2.10. Yes, I have CEST as time zone, but CEST is UTC+2 and not UTC+0.

All the events are shown as all-day in Outlook:

![image](https://user-images.githubusercontent.com/5118924/236671324-2cc781a0-61cc-4181-9b3c-0abb43052d77.png)

In the details of the event in Outlook, I can see that it starts and ends at 00:00 of the same day:

![image](https://user-images.githubusercontent.com/5118924/236671482-12bbeaa2-9901-47fb-b9f7-9f7cbca78b59.png)

But in Home Assistant, it is shown as starting at 00:00 of the day and ending at 00:00 at the next day:

![image](https://user-images.githubusercontent.com/5118924/236671560-13632f06-533c-4c9d-8e21-c9393c5495c7.png)

**Comment by RogerSelwyn** [comment]
Not sure why it works for me, but I noticed it isn't flagged as all day internally when I pass data out to the core, so I'm just trying to fix that.

**Comment by RogerSelwyn** [comment]
Please try the latest release to validate this issue has been fixed. If not fixed, please re-open.

https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.2.11

**Comment by jensrossbach** [comment]
The problem seems to be fixed by your change, thanks a lot!

But unfortunately now I get error messages on the calendar card that calendar events couldn't be downloaded (although they actually seem to be loaded).

![image](https://user-images.githubusercontent.com/5118924/236693380-f3f9b89d-4f18-4d40-8011-faf15ffd8ce4.png)

**Comment by RogerSelwyn** [comment]
Please look in your logs to see if any errors show there

**Comment by jensrossbach** [comment]
Logger: aiohttp.server
Source: components/calendar/__init__.py:552 
First occurred: 19:33:28 (19 occurrences) 
Last logged: 20:09:27

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 552, in get
    [
TypeError: 'NoneType' object is not iterable

**Comment by RogerSelwyn** [comment]
Ok, that gives me something to go on. I would roll back to previous release until I fix it.

**Comment by RogerSelwyn** [comment]
Do you have an entry in all calendars, or is perhaps one empty (e.g. no birthdays this month)?

**Comment by jensrossbach** [comment]
Yes, there seems to be at least one event in every calendar in this month. But the error message seems only to occur in the day grid and the week list view, but not in the month grid view of the calendar card.

**Comment by RogerSelwyn** [comment]
Ok, that helps. I’ll look on the morning. I suspect one of those periods may be empty and my changes are sending back an invalid result.

**Comment by jensrossbach** [comment]
I just tested it and indeed the problem is fixed. No error badges on the calendar card and no error logs anymore. The original issue is also fixed.

Thank you very much for the fast feedback and fixing of the problem!
