### ISSUE TITLE
'NoneType' object has no attribute 'get_folder'

### ISSUE THREAD

**Issue by mplogas** [RogerSelwyn/O365-HomeAssistant#14]
**System:**
Home Assistant version: 2021.12.8
Plugin version: 2.2.7

**Plugin config:**
```yaml
o365:
  client_secret: !secret o365_clientsecret
  client_id: !secret o365_appid
  alt_auth_flow: true
  query_sensors:
    - name: "HA Notifications"
      folder: "Inbox/infrastructure/homeassistant"
      from: "<my mail address>"
      subject_contains: "Notifcation Home Assistant"
      has_attachment: True
      max_items: 2
      is_unread: True
```

HA error message:
```
Logger: homeassistant.components.sensor
Source: custom_components/o365/sensor.py:61
Integration: Sensor (documentation, issues)
First occurred: 7:58:30 PM (1 occurrences)
Last logged: 7:58:30 PM

Error while setting up o365 platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/o365/sensor.py", line 42, in setup_platform
    sensor = O365QuerySensor(account, conf)
  File "/config/custom_components/o365/sensor.py", line 61, in __init__
    self.mail_folder = self.mail_folder.get_folder(folder_name=folder)
AttributeError: 'NoneType' object has no attribute 'get_folder'
```

This error occurs during startup of HA. The calendar seem not affected, the mail folder Inbox/Infrastructure/homeassistant does exist.
![image](https://user-images.githubusercontent.com/842121/148824730-aa2c85a5-a58c-476f-87ff-159bd7215971.png)

**Comment by RogerSelwyn** [comment]
Don't use mail myself, but I'll try and figure it out

**Comment by mplogas** [comment]
I disabled mail for now but I'm happy to test or provide additional logs. Let me know if you need anything else

**Comment by RogerSelwyn** [comment]
I've just got to go through and enable email in my test environment, then I should be able to see what is going on. Been along time since I set up the permissions....

**Comment by mplogas** [comment]
You should be good by just adding the mail related API permissions and re-login. The consent will appear automatically. 
Alternatively, you could as well give admin consent to the entire permission set, so the re-login/new consent shouldn't be neccessary.

**Comment by RogerSelwyn** [comment]
Thanks, looks like I already granted it. I'll take a look in the morning, family time now.

**Comment by mplogas** [comment]
The infrastructure folder is inside the Inbox folder, so it's Inbox - infrastructure - homeassistant. 

However I noticed something strange: I just checked using the Graph Explorer (GET on https://graph.microsoft.com/beta/me/mailFolders/?includeHiddenFolders=true&$skip=20) and the folder id AND the parentfolder id are the same for all mail folders. what endpoint are you using with the Graph API? Maybe it's the same issue?

**Comment by RogerSelwyn** [comment]
The calls are made via O365 pypi library I believe so I’d have to look when I get back home, but I’m getting errors of a different type myself. If I just put a folder with no other query parameters or retrieves data fine, as soon as I add a parameter if tells me the work is too complex. I’m hoping to look at it some more

**Comment by RogerSelwyn** [comment]
It's calling here - 'https://graph.microsoft.com/v1.0/me/mailFolders', I can guide you to put a debug statement in to try and see where it is failing in the structure.

Line 56-61 replace with this and make sure debug logging is switched on for O365

```
        if mail_folder:
            for i, folder in enumerate(mail_folder.split("/")):
                _LOGGER.debug(f"Processing folder - {folder}")
                if i == 0:
                    self.mail_folder = self.mailbox.get_folder(folder_name=folder)
                else:
                    self.mail_folder = self.mail_folder.get_folder(folder_name=folder)
                _LOGGER.debug(f"Got folder id - {self.mail_folder.folder_id}")
```

Looking at the error line, it is trying to get a subfolder of the first or second in your hierarchy when it hasn't found the parent. I'll write an error logging line in to catch that, since it should be easy to detect.

**Comment by RogerSelwyn** [comment]
I've just released v2.2.8b2 which has the extra debug logging from above (modified slightly), plus some error handling to try to be more informative. Also fixes the filter error I mentioned above, which I'm surprised no-one has complained about. I found a blog from MS in 2016 detailing the change required, so maybe they only just enforced it 6 years on?

**Comment by mplogas** [comment]
I enabled debug for the component 
```yaml
logs:
  custom_components.o365: debug
```

updated to the latest beta (2.2.8b2) and received the following log:
```
2022-01-11 20:31:34 DEBUG (SyncWorker_8) [custom_components.o365.sensor] Processing folder - Inbox
2022-01-11 20:31:34 ERROR (SyncWorker_8) [custom_components.o365.sensor] Folder - Inbox - not found
2022-01-11 20:31:34 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up o365 platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/o365/sensor.py", line 44, in setup_platform
sensor = O365QuerySensor(account, conf)
File "/config/custom_components/o365/sensor.py", line 68, in __init__
raise ConfigEntryNotReady
homeassistant.exceptions.ConfigEntryNotReady: None
2022-01-11 20:31:34 DEBUG (MainThread) [custom_components.o365.calendar] No matching event found in the 0 results for Feiertage in Deutschland
2022-01-11 20:31:34 DEBUG (MainThread) [custom_components.o365.calendar] No matching event found in the 0 results for familie
```

Does that help?

**Comment by mplogas** [comment]
I just have been struck by an idea and was able to confirm it's the solution to my problem. I'm used to run my computer (and all my applications) in English, hence it's being called Inbox in my Outlook. However, I realized the **actual** name of the Inbox might be localized on the O365 Servers as my tenant is located in Germany, therefor my Inbox is named "Posteingang".
When renaming this to Posteingang/infrastructure/homeassistant no error is thrown:

```
2022-01-11 20:37:13 DEBUG (SyncWorker_1) [custom_components.o365.sensor] Processing folder - Posteingang
2022-01-11 20:37:13 DEBUG (SyncWorker_1) [custom_components.o365.sensor] Got folder id - <redacted>
2022-01-11 20:37:13 DEBUG (SyncWorker_1) [custom_components.o365.sensor] Processing folder - infrastructure
2022-01-11 20:37:13 DEBUG (SyncWorker_1) [custom_components.o365.sensor] Got folder id - <redacted>
2022-01-11 20:37:13 DEBUG (SyncWorker_1) [custom_components.o365.sensor] Processing folder - homeassistant
2022-01-11 20:37:13 DEBUG (SyncWorker_1) [custom_components.o365.sensor] Got folder id - <redacted>
2022-01-11 20:37:14 DEBUG (SyncWorker_1) [custom_components.o365.sensor] Filter: receivedDateTime ge 1900-05-01T00:00:00+00:00 and contains(subject, 'Notifcation Home Assistant') and hasAttachments eq true and from/emailAddress/address eq '<redacted>' and isRead eq false
Order: receivedDateTime desc
Select: None
Expand: None
Search: None
2022-01-11 20:37:14 DEBUG (MainThread) [custom_components.o365.calendar] No matching event found in the 0 results for Feiertage in Deutschland
2022-01-11 20:37:14 DEBUG (MainThread) [custom_components.o365.calendar] No matching event found in the 0 results for familie
```

So, it seems the name of Inbox depending on the region of the tenant and only later translated within Outlook/OWA.

**Comment by RogerSelwyn** [comment]
Well you learn something new each day

**Comment by RogerSelwyn** [comment]
As an fyi whilst I'm passing through the code I'm adding importance as a filter, also outputting importance and is_read in the data.

**Comment by mplogas** [comment]
I'll reach out to O365 PG and try to get a confirmation, but for now we can close this. If PG gets back and confirms, this might be something for the documentation of the component.
