### ISSUE TITLE
Feature request: Calling a Home Assistant service 

### ISSUE THREAD

**Issue by RikMuilwijk** [RogerSelwyn/O365-HomeAssistant#145]
This is the only integration I could find that can call a couple HA services via Office 365.

I have a HA instance inside the company network, that I would like to control from Office 365. All I need is to call a few basic services (turn input booleans on/off). Would this be possible through this integration?

My idea is to write a PowerApp that controls the Home Assistant instance in order to give my colleagues secure acces to this HA instance.

**Comment by RogerSelwyn** [comment]
O365 does not call HA services via this integration, the O365 Integration uses HA services to perform actions on the O365 API.

That said, since this integration monitors emails (on a polling basis), you could write automations that monitor an email sensor and then perform actions on HA.

Not sure if that helps.

**Comment by luizokss** [comment]
Hi, can you give a help ? 
I can't get past this stage


![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/96143782/7b248f57-93b0-4b82-b2e8-3b8e085e26e3)


receiving this log message.

Este erro originou-se de uma integração personalizada.

Logger: aiohttp.server
Source: custom_components/o365/utils.py:167
Integration: Office 365 (documentation, issues)
First occurred: 10:38:01 (2 occurrences)
Last logged: 10:41:58

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/repairs/websocket_api.py", line 106, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 233, in async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/components/repairs/issue_handler.py", line 78, in async_create_flow
    flow = await platform.async_create_fix_flow(self.hass, issue_id, issue.data)
  File "/config/custom_components/o365/repairs.py", line 166, in async_create_fix_flow
    return AuthorizationRepairFlow(hass, data)
  File "/config/custom_components/o365/repairs.py", line 54, in __init__
    scope = build_requested_permissions(self._conf)
  File "/config/custom_components/o365/utils.py", line 167, in build_requested_permissions
    scope.append(PERM_CALENDARS_READ + shared)
TypeError: can only concatenate str (not "NoneType") to str

**Comment by RogerSelwyn** [comment]
Upgrade to latest beta which should fix this

**Comment by RogerSelwyn** [comment]
oops, don't think it is in there

**Comment by RogerSelwyn** [comment]
Upgrade to v4.3.2

**Comment by luizokss** [comment]
It works.

thx

 

De: RogerSelwyn ***@***.***> 
Enviada em: sábado, 3 de junho de 2023 12:43
Para: RogerSelwyn/O365-HomeAssistant ***@***.***>
Cc: luizokss ***@***.***>; Comment ***@***.***>
Assunto: Re: [RogerSelwyn/O365-HomeAssistant] Feature request: Calling a Home Assistant service (Issue #145)

 

Upgrade to v4.3.2

**Comment by RogerSelwyn** [comment]
Closing since no more comments
