### ISSUE TITLE
Token Expired.

### ISSUE THREAD

**Issue by los7702** [RogerSelwyn/O365-HomeAssistant#148]
I "accedently" revoked all my tokens for my account when trying too troublesshoot an ather issue.
This resultetd ofcourse the revokation of this integrations current aut token as well :-)

Problem is that there are no new "Repair" so i cant easaly reauthenticate the integration...
Any idea?
also tried with latest version 4.3.2

Pasting text from HA log..
Best regards...

Logger: homeassistant.components.sensor
Source: custom_components/o365/sensor.py:645
Integration: Sensor (documentation, issues)
First occurred: 08:08:49 (1 occurrences)
Last logged: 08:08:49

Error while setting up o365 platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/O365/connection.py", line 753, in _internal_request
    response = request_obj.request(method, url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 483, in request
    url, headers, data = self._client.add_token(
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 217, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/o365/sensor.py", line 108, in async_setup_platform
    entities = await coordinator.async_setup_entries()
  File "/config/custom_components/o365/sensor.py", line 143, in async_setup_entries
    todo_entities = await self._async_todo_sensors()
  File "/config/custom_components/o365/sensor.py", line 248, in _async_todo_sensors
    await sensor_services.async_scan_for_task_lists(None)
  File "/config/custom_components/o365/sensor.py", line 645, in async_scan_for_task_lists
    todolists = await self._hass.async_add_executor_job(todos.list_folders)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/O365/tasks_graph.py", line 701, in list_folders
    response = self.con.get(url, params=params or None)
  File "/usr/local/lib/python3.10/site-packages/O365/connection.py", line 865, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/O365/connection.py", line 854, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/O365/connection.py", line 770, in _internal_request
    if self.refresh_token() is False:
  File "/usr/local/lib/python3.10/site-packages/O365/connection.py", line 671, in refresh_token
    self.session.refresh_token(
  File "/usr/local/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 452, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.10/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2022-10-16T07:52:02.8390570Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2023-06-01T16:03:41.0000000Z'.
Trace ID: 85122e2b-4be7-4aed-a8b2-044b2107fd00
Correlation ID: 7bd048dc-7ecf-411f-8ea5-c453fa965efe
Timestamp: 2023-06-07 06:08:49Z

**Comment by RogerSelwyn** [comment]
Make sure there is time left on your client secret in the azure portal, if not then create a new secret and update your config with the id and secret. Delete your token, then reboot a HA. You should then get the repair prompt.

**Comment by los7702** [comment]
Can you paint me to where i delete my token?

**Comment by los7702** [comment]
Thanks... :-)
Im on to creating a frontend card repository (slowly progressing...)
