### ISSUE TITLE
voluptuous.error.MultipleInvalid: expected a list for dictionary value @ data['accounts']

### ISSUE THREAD

**Issue by xaxix** [RogerSelwyn/O365-HomeAssistant#153]
The installation via HACS ran without errors. The o365 configuration I have swapped into a 0365.yaml and included it per include in the configuration.yaml. I use only one personal account. Unfortunately I get the following error:

```
Error during setup of component o365
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/o365/__init__.py", line 62, in async_setup
    accounts = MULTI_ACCOUNT_SCHEMA(conf)[CONF_ACCOUNTS]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected a list for dictionary value @ data['accounts']
```

My config looks like this:
```
accounts:
    account_name: Bastian # Do not use email address or spaces
    client_id: "xxxxxxx"
    client_secret: "xxxxxx"
    alt_auth_method: False
    enable_update: False #keine Schreibrechte im Kalender oder bei E-Mail
    track_new_calendar: True
#    email_sensor:
#        - name: inbox
#          max_items: 2
#          is_unread: True
#          download_attachments: False
#    query_sensors:
#        - name: "Example"
#          folder: "Inbox/Test_Inbox" #Default is Inbox
#          from: "bastian@example.com"
#          subject_contains: "Example subject"
#          has_attachment: True
#          max_items: 2
#          is_unread: True
    todo_sensors:
        enabled: False
```

**Comment by RogerSelwyn** [comment]
Plus carefully look at the structure here https://rogerselwyn.github.io/O365-HomeAssistant/installation_and_configuration.html

Formatting in yaml is important, there should be a ‘-‘ before account_name, and all below indented. 

I’m on holiday, so not looked carefully, but I can see that is wrong.

**Comment by xaxix** [comment]
Thank you so much! It was the missing "-". Have a nice holiday!
