### ISSUE TITLE
404 Client Error

### ISSUE THREAD

**Issue by nickpieters** [RogerSelwyn/O365-HomeAssistant#169]
Hi 

Seems I'm having another issue. 

The token is requested fine. But not data is coming in or at least i cannot see any sensor info. 

Below the config and 2 logs i can find, any pointers i could check to resolve this?

Thanks

```
o365:
  accounts:
    - account_name: usernamewithoutthemaildomain # Do not use email address or spaces
      client_id: "redacted"
      client_secret: "redacted"
      alt_auth_method: False
      enable_update: True
      email_sensor:
        - name: Inbox
          max_items: 2
          is_unread: True
          download_attachments: False
      query_sensors:
        - name: "Inbox"
          folder: "Inbox" #Default is Inbox
          from: "name@redacted.com"
          subject_contains: "Example subject"
          has_attachment: True
          max_items: 2
          is_unread: True
      status_sensors: # Cannot be used for personal accounts
        - name: "User Teams Status"
      chat_sensors: # Cannot be used for personal accounts
        - name: "User Chat"
      todo_sensors:
        enabled: True
```

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:359
Integration: Sensor (documentation, issues)
First occurred: 3:24:45 PM (1 occurrences)
Last logged: 3:24:45 PM

Error while setting up o365 platform for sensor
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/O365/connection.py", line 754, in _internal_request
    response.raise_for_status()  # raise 4XX and 5XX error codes.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://graph.microsoft.com/v1.0/me/mailFolders?%24filter=displayName+eq+%27Inbox%27&%24top=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/o365/sensor.py", line 104, in async_setup_platform
    entities = await coordinator.async_setup_entries()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/sensor.py", line 136, in async_setup_entries
    query_entities = await self._async_query_sensors()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/sensor.py", line 188, in _async_query_sensors
    if mail_folder := await self._async_get_mail_folder(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/sensor.py", line 310, in _async_get_mail_folder
    return await self._async_get_configured_mail_folder(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/sensor.py", line 321, in _async_get_configured_mail_folder
    mail_folder = await self.hass.async_add_executor_job(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/mailbox.py", line 549, in get_folder
    response = self.con.get(url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/connection.py", line 865, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/connection.py", line 854, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/connection.py", line 796, in _internal_request
    error.get("error", {}).get("innerError", "").get("code", "")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

```

```
Logger: homeassistant.components.calendar
Source: helpers/entity_platform.py:359
Integration: Calendar (documentation, issues)
First occurred: 3:12:33 PM (1 occurrences)
Last logged: 3:12:33 PM

Error while setting up o365 platform for calendar
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/O365/connection.py", line 754, in _internal_request
    response.raise_for_status()  # raise 4XX and 5XX error codes.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://graph.microsoft.com/v1.0/me/calendars

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/o365/calendar.py", line 118, in async_setup_platform
    await _async_setup_register_services(hass, update_supported)
  File "/config/custom_components/o365/calendar.py", line 181, in _async_setup_register_services
    await calendar_services.async_scan_for_calendars(None)
  File "/config/custom_components/o365/calendar.py", line 712, in async_scan_for_calendars
    calendars = await self._hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/calendar.py", line 1897, in list_calendars
    response = self.con.get(url, params=params or None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/connection.py", line 865, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/connection.py", line 854, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/connection.py", line 796, in _internal_request
    error.get("error", {}).get("innerError", "").get("code", "")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

```

**Comment by RogerSelwyn** [comment]
Can I suggest you remove all the extra queries until you know you have the base working. The minimum you need for calendars is:

```
o365:
  accounts:
    - account_name: usernamewithoutthemaildomain # Do not use email address or spaces
      client_id: "redacted"
      client_secret: "redacted"
```

**Comment by RogerSelwyn** [comment]
Looking at the errors, it suggests you don't have access to the api. It's not clear to me why, so I would delete the Azure App, and reset up ensuring you have followed the instructions.
