### ISSUE TITLE
Component fails to set up

### ISSUE THREAD

**Issue by spitfire** [RogerSelwyn/O365-HomeAssistant#176]
I had this working for a few months now, and recently (presumably after update to 4.4.2) it stopped working displaying following error:
```
Logger: homeassistant.setup
Source: setup.py:288
First occurred: 15:27:06 (1 occurrences)
Last logged: 15:27:06

Error during setup of component o365
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/o365/__init__.py", line 64, in async_setup
    await _async_setup_account(hass, account, conf_type)
  File "/config/custom_components/o365/__init__.py", line 154, in _async_setup_account
    is_authenticated = account.is_authenticated
                       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/account.py", line 79, in is_authenticated
    token = self.con.token_backend.get_token()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/utils/token.py", line 94, in get_token
    self.token = self.load_token()  # store the token in the 'token' property
                 ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/utils/token.py", line 240, in load_token
    token = self.token_constructor(self.serializer.load(token_file))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

I went ahead and tried setting up the secret again, re-checked my permissions (granted pretty much everything).

here's my (previously working) config:
```
o365:
  accounts:
    - account_name: <redacted>
      client_id: !secret o365_client_id <"Application (client) ID" from Azure>
      client_secret: !secret o365_client_secret  <"Value" from Client secrets in Azure, newly generated just to be sure.>
      alt_auth_method: False
      enable_update: True
      track_new_calendar: True
      auto_reply_sensors:
        - name: auto_reply
      email_sensor:
        - name: inbox
          max_items: 10 #2
          is_unread: True
          download_attachments: False
      # query_sensors:
      #   - name: "Inbox"
      #     from: !secret o365_email
      #     subject_contains: "Example subject"
      #     has_attachment: True
      #     max_items: 2
      #     is_unread: True
      status_sensors: # Cannot be used for personal accounts
        - name: "User Teams Status"
      chat_sensors: # Cannot be used for personal accounts
        - name: "User Chat"
      todo_sensors:
        enabled: True
```

Following that I've also tried upgrading to 4.4.3b2 and restarting HA, same error.

**Comment by RogerSelwyn** [comment]
It looks like your token is corrupt, so you need to delete it from here - `<config>/o365_storage/.O365-token-cache`

Alternatively rollback to your previously working version o the integration and report back here on whether it works or not.

**Comment by spitfire** [comment]
Downgrading itself didn't help.
I've:
- Downgraded to 4.4.2
- Removed the /config/o365_storage/.O365-token-cache directory
- Reauthenticated as instructed by HA flow
and now it's working, thanks.

I didn't see anything about that token, it might be useful to add it to some FAQ
