### ISSUE TITLE
Group Calendar not working after import

### ISSUE THREAD

**Issue by macrauder** [RogerSelwyn/O365-HomeAssistant#181]
I run version 4.5.0.b3 with a configured group calender. The first import is fine and I can display the calendar with the regular o365 calendars in the atomic-calendar-revive component. In the normal calendar component I didn't get my group calendar and in the logs i get the following error.

`
Logger: homeassistant
Source: custom_components/o365/calendar.py:259
Integration: Office 365 ([documentation](https://github.com/RogerSelwyn/O365-HomeAssistant), [issues](https://github.com/RogerSelwyn/O365-HomeAssistant/issues))
First occurred: 20:58:30 (5 occurrences)
Last logged: 21:01:30

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1153, in _async_registry_updated
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 530, in async_write_ha_state
    super().async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 787, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/calendar.py", line 259, in extra_state_attributes
    ATTR_COLOR: self.data.calendar.color,
                ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Schedule' object has no attribute 'color'
`

**Comment by RogerSelwyn** [comment]
I am very unlikely to get this fixed for about 3 weeks. I’d suggest going back to the previous version that worked for you.

**Comment by RogerSelwyn** [comment]
Or just comment out line 259 in calendar.py. You may need to also comment or 261/2 as well.

**Comment by macrauder** [comment]
thx, i fixed it locally and it is working.
