### ISSUE TITLE
Error Message: Failed to get license information for the user. Ensure user has a valid Office365 license assigned to them.

### ISSUE THREAD

**Issue by Jaykurb** [RogerSelwyn/O365-HomeAssistant#183]
This integration was working fine for a week or so, and then it was unable to fetch the data.

error:

```
Logger: homeassistant.setup
Source: setup.py:288
First occurred: 11:35:34 (1 occurrences)
Last logged: 11:35:34

Error during setup of component o365
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/coordinator.py", line 301, in _async_update_data
    await self._async_teams_chat_update(key)
  File "/config/custom_components/o365/coordinator.py", line 344, in _async_teams_chat_update
    chats = await self.hass.async_add_executor_job(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/teams.py", line 760, in get_my_chats
    response = self.con.get(url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/connection.py", line 865, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/connection.py", line 854, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/connection.py", line 816, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/me/chats?%24top=20 | Error Message: Failed to get license information for the user. Ensure user has a valid Office365 license assigned to them.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/o365/__init__.py", line 64, in async_setup
    await _async_setup_account(hass, account, conf_type)
  File "/config/custom_components/o365/__init__.py", line 169, in _async_setup_account
    await do_setup(hass, account_conf, account, account_name, conf_type, perms)
  File "/config/custom_components/o365/setup.py", line 56, in do_setup
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 262, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/me/chats?%24top=20 | Error Message: Failed to get license information for the user. Ensure user has a valid Office365 license assigned to them.
```

**Comment by Jaykurb** [comment]
For some reason, I didn't have an O365-token-cache folder in the o365_storage directory. So I deleted everything (integration, yaml, App registration, secrets etc) and started from scratch, but I keep getting the following error:

```
Logger: O365.connection
Source: /usr/local/lib/python3.11/site-packages/O365/connection.py:563
First occurred: 17:10:00 (2 occurrences)
Last logged: 17:10:50

Unable to fetch auth token. Error: (invalid_grant) AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token. Trace ID: db145175-cb6c-4aab-9b3f-312a52cf1d00 Correlation ID: 669e7cfd-a027-4540-832c-2ff5de102525 Timestamp: 2023-12-02 17:10:00Z
Unable to fetch auth token. Error: (invalid_grant) AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token. Trace ID: 30c81826-860b-47b1-9f9d-41a21a921c00 Correlation ID: 57b285c8-264a-4073-bf79-c2a7944a40e3 Timestamp: 2023-12-02 17:10:50Z
```

**Comment by RogerSelwyn** [comment]
Note that the .O365-token-cache folder has a dot on the start, so it is hidden. You may not see it without depending on how you are looking for it.

Without the token it would never have been working, it would have prompted for a repair to get authorisation. Make sure when you try to reinstall, that you follow the repair authorisation flow to conclusion. You must immediately copy the url returned into the box provided.

My suspicion is that you have a token in place, which doesn't match the client_id/secret. To be honest I have no idea what error that would generate.

**Comment by RogerSelwyn** [comment]
You wouldn't get a repair if you had uninstalled it, the repair is part of the install mechanism. Please, just delete the token, rebbotand follow the install instructions. Don't worry about the time on the repair, just use what is there. I have no idea what the CSRF error is.

**Comment by Jaykurb** [comment]
I have tried this a fair few times, but I get the same issue when authenticating every time. I have added a video to show how it reacts and I have also attached the errors provided in the logs.

https://github.com/RogerSelwyn/O365-HomeAssistant/assets/49797976/788a7f0d-cfab-4f27-97b8-938b7eb42ab2

```
Logger: O365.connection
Source: /usr/local/lib/python3.11/site-packages/O365/connection.py:806
First occurred: 11:50:15 (1 occurrences)
Last logged: 11:50:15

Client Error: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/me/chats?%24top=20 | Error Message: Failed to get license information for the user. Ensure user has a valid Office365 license assigned to them. | Error Code:
```

```
Logger: O365.connection
Source: /usr/local/lib/python3.11/site-packages/O365/connection.py:563
First occurred: 11:50:17 (1 occurrences)
Last logged: 11:50:17

Unable to fetch auth token. Error: (invalid_grant) AADSTS54005: OAuth2 Authorization code was already redeemed, please retry with a new valid code or use an existing refresh token. Trace ID: 81363683-afa4-4dbf-aa65-2ffee4461400 Correlation ID: 83cc9a0d-ca7e-4b3b-b51e-6e0b361399f6 Timestamp: 2023-12-04 11:50:17Z
```

**Comment by RogerSelwyn** [comment]
The second error (invalid grant) is because you clicked submit twice (I haven't tested, but I'd expect that to be the case). Try removing the Teams Chat sensor from your config since that is what is generating the error.
