### ISSUE TITLE
Authorisation Error

### ISSUE THREAD

**Issue by anti-spy** [RogerSelwyn/O365-HomeAssistant#188]
I can’t log into my account, it says permissions are not granted.  however, I did everything according to the instructions.  All permissions are given as indicated in the instructions.  I watched the video as they insist, I did everything the same.

Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:421
First occurred: 07:25:10 (1 occurrences)
Last logged: 07:25:10

Error handling request
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/coordinator.py", line 301, in _async_update_data
    await self._async_teams_chat_update(key)
  File "/config/custom_components/o365/coordinator.py", line 344, in _async_teams_chat_update
    chats = await self.hass.async_add_executor_job(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/teams.py", line 760, in get_my_chats
    response = self.con.get(url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/connection.py", line 865, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/connection.py", line 854, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/O365/connection.py", line 816, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/me/chats?%24top=20 | Error Message: No authorization information present on the request.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/repairs/websocket_api.py", line 135, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 389, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/repairs.py", line 77, in async_step_request_default
    errors = await self._async_validate_response(user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/repairs.py", line 156, in _async_validate_response
    await do_setup(
  File "/config/custom_components/o365/setup.py", line 56, in do_setup
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 272, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/me/chats?%24top=20 | Error Message: No authorization information present on the request.

Logger: custom_components.o365.classes.permissions
Source: custom_components/o365/classes/permissions.py:127
Integration: Office 365 (documentation, issues)
First occurred: 09:33:32 (1 occurrences)
Last logged: 09:33:32

Minimum required permissions not granted: Presence.Read, Chat.Read

Logger: O365.connection
Source: /usr/local/lib/python3.11/site-packages/O365/connection.py:806
First occurred: 09:33:35 (1 occurrences)
Last logged: 09:33:35

Client Error: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/me/chats?%24top=20 | Error Message: No authorization information present on the request. | Error Code:

Logger: custom_components.o365.coordinator
Source: custom_components/o365/coordinator.py:281
Integration: Office 365 (documentation, issues)
First occurred: 07:25:07 (1 occurrences)
Last logged: 07:25:07

Folder - Inbox - not found from query_sensors config entry - Inbox/Test_Inbox - entity not created

![Screenshot_20231228-093337_Home Assistant](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/97808357/ec79da60-28c3-4223-9a34-e3549ee2bbbb)

**Comment by RogerSelwyn** [comment]
My guess is you are using a personal account and you have configured teams chat and presence sensors. As a starting point, just configure the minimum so you know you have a working connection to O365.

```
o365:
  accounts:
    - account_name: Account1 # Do not use email address or spaces
      client_id: "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx"
      client_secret: "xx.xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
```

**Comment by anti-spy** [comment]
Yes, just a regular personal account, I don’t have a corporate account.  Of all the functions I only need to do.  I tried as you wrote.  There is no login window then.

**Comment by RogerSelwyn** [comment]
Sorry, I don't understand. I can see from the permissions it is saying it is missing (in the screenshot) that you have Teams Chat and Teams Status enabled. The documentation is very that you can't use these for a personal account. Please disable them, and then try again. If it still fails, please post back here.

**Comment by RogerSelwyn** [comment]
You also have an additional error with regards a query sensor. Have you got an `Inbox_Test` inside your `Inbox` folder?

**Comment by anti-spy** [comment]
everything is working!  thank you very much)
