### ISSUE TITLE
Invalid combinations for Teams presence status 

### ISSUE THREAD

**Issue by NightMean** [RogerSelwyn/O365-HomeAssistant#208]
Hi, I've just downloaded the `4.7.0b1` where I'm trying to update my Teams presence status. 
The feature works however some combinations can't be called by the service. 

Eg. `Availability: Available` + `Activity: In Call/In a Conference Call/Away/Presenting`
Or `Availability: Busy` + `Activity: Available/Away/Presenting`

Is there a possibility to only show possible variations when selecting Availability ?
Also, what I found is that `Do Not Disturb` and `Away` can't be set as only Do Not Disturb/Away only. 
`Do Not Disturb` can only be set to Presenting activity. 
`Away`, while the service is being called correctly does not change it to Away. Not sure if this is API limitation or an issue with the feature itself. 

```python
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/o365/classes/teamssensor.py:88
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 11:32:26 (8 occurrences)
Last logged: 11:37:57

[140625181447616] Error handling message: Unknown error (unknown_error) NightMean from 192.168.1.101 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 795, in handle_execute_script
    script_result = await script_obj.async_run(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1600, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 435, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 487, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 512, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 485, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 723, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 685, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/classes/teamssensor.py", line 88, in update_user_status
    status = self.teams.set_my_presence(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/O365/teams.py", line 777, in set_my_presence
    response = self.con.post(url, data=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/O365/connection.py", line 886, in post
    return self.oauth_request(url, 'post', data=data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/O365/connection.py", line 864, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/O365/connection.py", line 826, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/presence/setPresence | Error Message: The provided availability/activity is invalid.
```

Related to #197

**Comment by NightMean** [comment]
Understood, thank you. Might be worth adding that to the documentation for reference. 
Any reason why the `setuserpreferredpresence` was not used instead? That seems to support changing to DND/Away and so on. With `setPresence` it does not override the Teams status set by the user in the app/web

https://learn.microsoft.com/en-us/graph/api/presence-setuserpreferredpresence?view=graph-rest-1.0&tabs=http

**Comment by RogerSelwyn** [comment]
I'll add an extra service, to do preferred status. Set Status is to give Teams a clue based on that application as to what the status should be. Set Preferred Status is equivalent to doing it in Teams itself.

I have to correct an error in the underlying library to add the extra service.

**Comment by NightMean** [comment]
Perfect, much appreciated. 
Thank you!

**Comment by RogerSelwyn** [comment]
New service should be available in beta 2 - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.7.0b2
