### ISSUE TITLE
Update fails error in logs and O65 integration not shows in integration UI of HA

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [RogerSelwyn/O365-HomeAssistant#236]
**After doing several restarts of HA today i got the following error in my logs AND also the O365 integration not anymore shows in the integration UI of HA**

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:950
First occurred: 22:04:02 (1 occurrences)
Last logged: 22:04:02

Update for calendar.cam4_agenda_cam4 fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/O365/connection.py", line 785, in _internal_request
    response = request_obj.request(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests_oauthlib/oauth2_session.py", line 483, in request
    url, headers, data = self._client.add_token(
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 217, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 950, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1293, in async_device_update
    await self.async_update()
  File "/config/custom_components/o365/calendar.py", line 297, in async_update
    await self.data.async_update(self.hass)
  File "/config/custom_components/o365/calendar.py", line 665, in async_update
    results = await self.async_o365_get_events(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/calendar.py", line 560, in async_o365_get_events
    events = await self._async_calendar_schedule_get_events(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/calendar.py", line 623, in _async_calendar_schedule_get_events
    return await hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/O365/calendar.py", line 1797, in get_events
    response = self.con.get(url, params=params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/O365/connection.py", line 898, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/O365/connection.py", line 887, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/O365/connection.py", line 802, in _internal_request
    if self.refresh_token() is False:
       ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/O365/connection.py", line 699, in refresh_token
    self.session.refresh_token(
  File "/usr/local/lib/python3.12/site-packages/requests_oauthlib/oauth2_session.py", line 452, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.12/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.12/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.TemporarilyUnavailableError: (temporarily_unavailable) AADSTS70012: The request could not be completed. Please try again later. Trace ID: 8fe1c655-4df4-4460-bbee-cce0f1f1fe00 Correlation ID: ce95730f-334e-409d-a6ff-76e7bb52243f Timestamp: 2024-06-05 19:04:02Z

**Comment by RogerSelwyn** [comment]
Your token has expired as stated in the error, delete and re-authenticate - https://github.com/RogerSelwyn/O365-HomeAssistant/blob/master/docs/token.md

**Comment by smarthomefamilyverrips** [comment]
> Your token has expired as stated in the error, delete and re-authenticate - https://github.com/RogerSelwyn/O365-HomeAssistant/blob/master/docs/token.md

Ok did do that, it did pass the re-auth succesful but I still not see the O365 integration on the page with installed integrations of HA, do I need to do a other restart of HA for the integration to show up again in the list with integrations?

**Comment by RogerSelwyn** [comment]
It is never on there because it is configured via yaml

**Comment by smarthomefamilyverrips** [comment]
> It is never on there because it is configured via yaml

OK now I gonna sound like a idiot but I would swear it was there before at me, showing the Office Logo with O365 text and could see the amount of calendar entities at the bottom..... Am I going crazy now?????? 🫣

**Comment by RogerSelwyn** [comment]
No idea

**Comment by smarthomefamilyverrips** [comment]
> No idea

Probably yes :))))

Thanl you anyway! I am looking forward totry out the stand-alone version of the O365 Calendar 👍

**Comment by smarthomefamilyverrips** [comment]
close as solved
