### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by warmbo** [RogerSelwyn/O365-HomeAssistant#261]
Hello, I am trying to set this integration up with a personal account. I struggled with authentication, but now that I have the correct URI in place and my reverse proxy configured for HA, I am receiving a new error without any documentation about it. The .token file is created when I get this error what looks successfully. I'm not able to do anything once this error occurs. Every other integration works via the proxy as best I can tell.

```
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 6:03:11 PM (1 occurrences)
Last logged: 6:03:11 PM

Error handling request
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
  |     resp = await request_handler(request)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
  |     resp = await handler(request)
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
  |     return await handler(request)
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
  |     return await handler(request)
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
  |     return await handler(request)
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
  |     return await handler(request)
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
  |     return await handler(request)
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
  |     return await handler(request)
  |            ^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
  |     response = await handler(request)
  |                ^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
  |     result = await handler(request, **request.match_info)
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
  |     return await func(self, request, *args, **kwargs)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/src/homeassistant/homeassistant/components/repairs/websocket_api.py", line 162, in post
  |     return await super().post(request, flow_id)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
  |     result = await method(view, request, data, *args, **kwargs)
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
  |     result = await self._flow_mgr.async_configure(flow_id, data)
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 358, in async_configure
  |     result = await self._async_configure(flow_id, user_input)
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 404, in _async_configure
  |     result = await self._async_handle_step(
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 501, in _async_handle_step
  |     result: FlowResult = await getattr(flow, method)(user_input)
  |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/config/custom_components/o365/repairs.py", line 103, in async_step_request_alt
  |     errors = await self._async_validate_response(user_input)
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/config/custom_components/o365/repairs.py", line 164, in _async_validate_response
  |     await do_setup(
  |   File "/config/custom_components/o365/helpers/setup.py", line 66, in do_setup
  |     async with asyncio.TaskGroup() as group:
  |   File "/usr/local/lib/python3.12/asyncio/taskgroups.py", line 145, in __aexit__
  |     raise me from None
  | ExceptionGroup: unhandled errors in a TaskGroup (2 sub-exceptions)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/config/custom_components/o365/helpers/setup.py", line 84, in _async_sensor_setup
    |     sensor_coordinator = O365SensorCordinator(hass, account_config)
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/config/custom_components/o365/helpers/coordinator.py", line 89, in __init__
    |     1, 1, 1, 0, 0, 0, tzinfo=dt_util.get_default_time_zone()
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | AttributeError: module 'homeassistant.util.dt' has no attribute 'get_default_time_zone'. Did you mean: 'set_default_time_zone'?
    +---------------- 2 ----------------
    | Traceback (most recent call last):
    |   File "/config/custom_components/o365/helpers/setup.py", line 94, in _async_email_setup
    |     email_coordinator = O365EmailCordinator(hass, account_config)
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/config/custom_components/o365/helpers/coordinator.py", line 401, in __init__
    |     1, 1, 1, 0, 0, 0, tzinfo=dt_util.get_default_time_zone()
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | AttributeError: module 'homeassistant.util.dt' has no attribute 'get_default_time_zone'. Did you mean: 'set_default_time_zone'?
    +------------------------------------
```

**Comment by RogerSelwyn** [comment]
You need to upgrade your version of HA, I think to 2024.6.x at minimum
