### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by rgerbranda** [RogerSelwyn/O365-HomeAssistant#39]
Hi,

Since yesterday the integration will not run anymore. This is the log.

Can you help me out?

```
2022-04-22 07:32:10 ERROR (MainThread) [homeassistant.setup] Error during setup of component o365
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
result = await task
File "/config/custom_components/o365/__init__.py", line 65, in async_setup
_setup_account(hass, account, conf_type)
File "/config/custom_components/o365/__init__.py", line 84, in _setup_account
is_authenticated = account.is_authenticated
File "/usr/local/lib/python3.9/site-packages/O365/account.py", line 69, in is_authenticated
token = self.con.token_backend.get_token()
File "/usr/local/lib/python3.9/site-packages/O365/utils/token.py", line 94, in get_token
self.token = self.load_token() # store the token in the 'token' property
File "/usr/local/lib/python3.9/site-packages/O365/utils/token.py", line 187, in load_token
token = self.token_constructor(self.serializer.load(token_file))
File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by RogerSelwyn** [comment]
It sounds to me like your token file is corrupted in some way. I'm guessing that since the error is at the start of the file, it may be empty.

I would try deleting or renaming your token file, found in .O365-token-cache folder. This will force it to request you to re-authenticate.

**Comment by rgerbranda** [comment]
I removed (1) the file, (2) the folder, (3) the configuration in configuration.yaml and (4) added the configuration again. Unfortunately it doesn't force to re-authenticate. 

Current error:

```
2022-04-23 10:13:46 WARNING (MainThread) [custom_components.o365.utils] Could not locate token at /config/.O365-token-cache/o365.token
2022-04-23 10:13:46 ERROR (MainThread) [homeassistant.setup] Error during setup of component o365
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/o365/__init__.py", line 65, in async_setup
    _setup_account(hass, account, conf_type)
  File "/config/custom_components/o365/__init__.py", line 90, in _setup_account
    _request_authorization(hass, account_conf, account, account_name, conf_type)
  File "/config/custom_components/o365/__init__.py", line 191, in _request_authorization
    callback_url = _get_callback_url(hass, alt_config)
  File "/config/custom_components/o365/__init__.py", line 213, in _get_callback_url
    return f"{get_url(hass, prefer_external=True)}{AUTH_CALLBACK_PATH}"
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 168, in get_url
    request_host = _get_request_host()
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 207, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
```

**Comment by RogerSelwyn** [comment]
I've seen someone have that error before, and to be honest I have no idea how to trigger that. It is something to do with your HASS config, where HA core can't provide the url to use.

In any case, for most people it is easier to use alt_auth = True when setting up, because then no direct access to your HA instance is required. This means the redirect_uri "https://login.microsoftonline.com/common/oauth2/nativeclient" on your Azure app.

**Comment by RogerSelwyn** [comment]
I've had a look at the HA core code and to be honest it's too complex for me to figure out why HA can't return an external url, but it will be something to do with your specific setup. As I said above better to use the alternate auth method.

**Comment by rgerbranda** [comment]
Thanks for the quick response. I changed the  redirect_uri to "https://login.microsoftonline.com/common/oauth2/nativeclient" and now it is working fine.
