### ISSUE TITLE
o365: Error on device update!

### ISSUE THREAD

**Issue by czornikk** [RogerSelwyn/O365-HomeAssistant#47]
Since version 3.1.0 I get following error after restarting Home Assistant (2022.5):

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    await task
  File "/config/custom_components/o365/calendar.py", line 209, in async_update
    start = O365CalendarData.to_datetime(event.start)
  File "/config/custom_components/o365/calendar.py", line 395, in to_datetime
    elif "date" in obj:
TypeError: argument of type 'datetime.date' is not iterable

**Comment by RogerSelwyn** [comment]
Ok. I’ll take a look over the next couple of days. Try downgrading to previous version which will still work on HA 2022.5

**Comment by RogerSelwyn** [comment]
I'm working on a fix, this impacts all day events
