### ISSUE TITLE
Error during setup of component o365

### ISSUE THREAD

**Issue by Dr-know** [RogerSelwyn/O365-HomeAssistant#67]
Hello,
i have a new HA installation latest version.
installed HACS and your o365 component

Created the config file and office 365 app integration in Azure
after reload (treyed many times) i get following error:

2022-08-23 12:38:23.714 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration o365 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-23 12:39:06.904 ERROR (MainThread) [homeassistant.setup] Error during setup of component o365
File "/config/custom_components/o365/__init__.py", line 41, in async_setup

Please advice ..

**Comment by RogerSelwyn** [comment]
Please post the full error stack from your logs, and a copy of your O365 config (with appropriate items redacted)

**Comment by Dr-know** [comment]
2022-08-23 12:38:23.714 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration o365 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-23 12:38:23.720 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration garbage_collection which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-23 12:38:23.726 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-23 12:38:23.732 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-08-23 12:38:53.296 WARNING (SyncWorker_5) [homeassistant.components.rpi_power.binary_sensor] Under-voltage was detected. Consider getting a uninterruptible power supply for your Raspberry Pi.
2022-08-23 12:39:03.096 WARNING (MainThread) [homeassistant.setup] Setup of automation is taking over 10 seconds.
2022-08-23 12:39:04.766 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform dlna_dmr is taking over 10 seconds.
2022-08-23 12:39:06.904 ERROR (MainThread) [homeassistant.setup] Error during setup of component o365
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
result = await task
File "/config/custom_components/o365/__init__.py", line 41, in async_setup
accounts = MULTI_ACCOUNT_SCHEMA(conf)[CONF_ACCOUNTS]
File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
return self._compiled([], data)
File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
return base_validate(path, iteritems(data), out)
File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['accounts'][0]['track_new_calender']

o365:
  accounts:
    - account_name: Office365-Mahieu-IT-Services
      client_id: "************************************" #here i set de application ID !
      client_secret: "***************************"
      alt_auth_method: False
      enable_update: True
      track_new_calender: True
      email_sensor:
        - name: inbox
          max_items: 2
          is_unread: True
          download_attachments: False
      status_sensors: # Cannot be used for personal accounts
        - name: "Teams Status"
      chat_sensors: # Cannot be used for personal accounts
        - name: "Teams Chat status"

**Comment by RogerSelwyn** [comment]
Please can you post your config properly formatted, just use the <> in the GitHub editor toolbar. Then I can see if your formatting is wrong. The error indicates there is something wrong with track_new_calendar key.

**Comment by Dr-know** [comment]
Hello, 
Sorry relative new at this ..

`o365:
  accounts:
    - account_name: Office365-Mahieu-IT-Services
      client_id: "29774fdc-2058-47a1-8585-08c6a907c1ff"
      client_secret: "c75bffe9-3aae-4000-8e5d-724e776c4fbe"
      alt_auth_method: False
      enable_update: True
      track_new_calender: True
      email_sensor:
        - name: inbox
          max_items: 2
          is_unread: True
          download_attachments: False
      status_sensors: # Cannot be used for personal accounts
        - name: "Teams Status"
      chat_sensors: # Cannot be used for personal accounts
        - name: "Teams Chat status"`

hope this is ok.

**Comment by Dr-know** [comment]
Hello,

i found a typo in "track_new_calendar_key" i wrote "track_new_calendEr_key"
i am native dutch speaking ...

thank you for pointing me in the good direction !
