### ISSUE TITLE
Tasks yaml not generating and getting issues with latest beta

### ISSUE THREAD

**Issue by JazzMan808** [RogerSelwyn/O365-HomeAssistant#86]
Hi Roger,

Just installed the latest beta of the plugin and edited the configuration.yaml to include 
      todo_sensors:
        enabled: true

I checked in the o365_storage folder and and no file was generated but I have also noticed I am getting the below errors:
2022-11-22 22:30:15.697 WARNING (MainThread) [custom_components.o365.utils] Minimum required permissions not granted: ['Presence.Read', []]
2022-11-22 22:30:15.701 WARNING (MainThread) [custom_components.o365] No token, or token doesn't have all required permissions; requesting authorization for account: Outlook
2022-11-22 22:30:41.426 ERROR (SyncWorker_3) [O365.connection] Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/meNone?%24filter=displayName+eq+%27Inbox%27&%24top=1 | Error Message: Resource not found for the segment 'meNone'.
2022-11-22 22:30:41.428 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up o365 platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/o365/sensor.py", line 79, in async_setup_platform
await _async_query_sensors(hass, account, add_entities, conf)
File "/config/custom_components/o365/sensor.py", line 112, in _async_query_sensors
if mail_folder := await hass.async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/o365/sensor.py", line 193, in _get_mail_folder
return _get_configured_mail_folder(mail_folder_conf, mailbox, sensor_type)
File "/config/custom_components/o365/sensor.py", line 202, in _get_configured_mail_folder
mail_folder = mailbox.get_folder(folder_name=folder)
File "/usr/local/lib/python3.10/site-packages/O365/mailbox.py", line 293, in get_folder
response = self.con.get(url, params=params)
File "/usr/local/lib/python3.10/site-packages/O365/connection.py", line 847, in get
return self.oauth_request(url, 'get', params=params, **kwargs)
File "/usr/local/lib/python3.10/site-packages/O365/connection.py", line 836, in oauth_request
return self._internal_request(self.session, url, method, **kwargs)
File "/usr/local/lib/python3.10/site-packages/O365/connection.py", line 798, in _internal_request
raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/meNone?%24filter=displayName+eq+%27Inbox%27&%24top=1 | Error Message: Resource not found for the segment 'meNone'.

**Comment by RogerSelwyn** [comment]
Please see this issue and the comment I put at the top of the latest beta release notes.

https://github.com/RogerSelwyn/O365-HomeAssistant/issues/85

**Comment by RogerSelwyn** [comment]
If you are wanting to just access the inbox, don't use the folder parameter. And then it should work.

**Comment by RogerSelwyn** [comment]
@JazzMan808 did this solve your problem?

**Comment by JazzMan808** [comment]
Hi Roger all working now!

And the tasks yaml also autopopulated. - Is there any way to show the due date of a task?

**Comment by RogerSelwyn** [comment]
Yes, to your edited question.... 😉
