### ISSUE TITLE
sensor.inbox unavailable

### ISSUE THREAD

**Issue by farao780** [RogerSelwyn/O365-HomeAssistant#91]
since couple of versions my e-mail inbox sensor is unavailable.
i have a simple inbox sensor:

accounts:
  - account_name: mail
    client_secret: "secret"
    client_id: "secret"
    alt_auth_method: False
    enable_update: True
    email_sensor:
      - name: inbox
        max_items: 2
        is_unread: True

tried followings: 
- deleted alt_auth_flow according to new doc
- deleted  old app id and secret, created a new one
- turned on logging and have the followings:

Logger: homeassistant.components.sensor
Source: util/async_.py:168
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 17:48:30 (1 occurrences)
Last logged: 17:48:30
o365: Error on device update!

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in async_device_update
    await task
  File "/config/custom_components/o365/sensor.py", line 261, in async_update
    attrs = [get_email_attributes(x, self._download_attachments) for x in data]
  File "/config/custom_components/o365/sensor.py", line 261, in <listcomp>
    attrs = [get_email_attributes(x, self._download_attachments) for x in data]
  File "/usr/local/lib/python3.10/site-packages/O365/mailbox.py", line 219, in <genexpr>
    messages = (self.message_constructor(
  File "/usr/local/lib/python3.10/site-packages/O365/message.py", line 296, in __init__
    self.attachments.download_attachments()
  File "/usr/local/lib/python3.10/site-packages/O365/utils/attachment.py", line 454, in download_attachments
    response = self._parent.con.get(url)
  File "/usr/local/lib/python3.10/site-packages/O365/connection.py", line 847, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/O365/connection.py", line 836, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/O365/connection.py", line 743, in _internal_request
    response = request_obj.request(method, url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests_oauthlib/oauth2_session.py", line 521, in request
    return super(OAuth2Session, self).request(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1293, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 219, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 180, in protected_loop_func
    check_loop(func, strict=strict)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 168, in check_loop
    raise RuntimeError(
RuntimeError: Blocking calls must be done in the executor or a separate thread; Use `await hass.async_add_executor_job()`; at custom_components/o365/sensor.py, line 261: attrs = [get_email_attributes(x, self._download_attachments) for x in data]

**Comment by RogerSelwyn** [comment]
If you can set download_attachments to false, it should start up. Then I'll work a fix.
